var mongoose = require('mongoose');

require('../mongodb_helper');
var Post = require('../../models/post');

describe('Post model', () => {
  beforeEach((done) => {
    mongoose.connection.collections.posts.drop(() => {
      done();
    });
  });

  it('has a message', () => {
    var post = new Post({ message: 'some message' });
    expect(post.message).toEqual('some message');
  });

  it('can list all posts', (done) => {
    Post.find((err, posts) => {
      expect(err).toBeNull();
      expect(posts).toEqual([]);
      done();
    });
  });

  it('can save a post', (done) => {
    const post = new Post({
      user_id: new mongoose.Types.ObjectId(),
      message: 'some message',
    });

    post.save((err) => {
      expect(err).toBeNull();

      Post.find((err, posts) => {
        expect(err).toBeNull();

        expect(posts[0]).toMatchObject({ message: 'some message' });
        done();
      });
    });
  });

  it('should have a createdAt and updatedAt property generated by timestamps', (done) => {
    const post = new Post({
      user_id: new mongoose.Types.ObjectId(),
      message: 'some message',
    });

    post.save((err) => {
      expect(err).toBeNull();

      Post.find((err, posts) => {
        expect(err).toBeNull();
        expect(posts[0].createdAt).toBeDefined();
        expect(posts[0].updatedAt).toBeDefined();
        done();
      });
    });
  });

  it('should have a user_id field', (done) => {
    const post = new Post({
      user_id: new mongoose.Types.ObjectId(),
      message: 'some message',
    });

    post.save((err) => {
      expect(err).toBeNull();
      Post.findById(post._id, (err, post) => {
        expect(err).toBeNull();
        expect(post.user_id).toBeDefined();
        done();
      });
    });
  });
});
